name: Update Dashboard
on:
  push:
    paths:
      - 'data.json' # Запуск при обновлении данных
  workflow_dispatch: # Позволяет запускать вручную или через API (n8n)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install pandas plotly
      - name: Run script
        run: python script.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git pull --rebase origin master # ЗАБИРАЕМ ИЗМЕНЕНИЯ ОТ n8n ПЕРЕД ПУШЕМ
          git add index.html
          git commit -m "Auto-update dashboard" || echo "No changes to commit"
          git push origin master
